//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactoryDBEntities : DbContext
    {
        public FactoryDBEntities()
            : base("name=FactoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeShift> EmployeeShift { get; set; }
        public virtual DbSet<Shift> Shift { get; set; }
      
    }

    public class User
    {
        public int ID { get; set; } 
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int NumOfActions { get; set; }
    }
    public class Department
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Manager { get; set; } //empID

    }
    public class Employee 
    {
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }    
        public int StartWorkYear { get; set; }
        public int DepartmentID { get; set; }
    }
    public class Shift
    {
        public int ID { get; set; }
        public DateTime Date { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set;}
    }
    public class EmployeeShift
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int ShiftID { get; set; }

    }
}
